channels:
- conda-forge
dependencies:
- aimsgb =1.1.0
- ase =3.22.1
- atomistics =0.1.20
- coverage
- codacy-coverage
- defusedxml =0.7.1
- h5py =3.10.0
- matplotlib-base =3.8.2
- mendeleev =0.15.0
- mp-api =0.39.4
- numpy =1.26.3
- pandas =2.1.4
- phonopy =2.21.0
- pint =0.23
- pyiron_base =0.6.20
- pyiron_atomistics =0.4.4
- pylammpsmpi =0.2.11
- pyscal =2.10.18
- scikit-learn =1.3.2
- scipy =1.11.4
- seekpath =2.1.0
- spglib =2.2.0
- structuretoolkit =0.0.17
- gpaw >=20
- jupyter
- lammps >=2021.05.27
- nglview
- ipywidgets <8  # conflict with NGLview
- papermill
- seaborn
- sphinxdft >=3.0
- sphinxdft-data
- iprpy-data
- pyiron-data >=0.0.26
- sqsgenerator
- gpaw =23.9.1
- pip
